# Generated by Django 2.0 on 2019-08-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiryform',
            options={},
        ),
    ]
