# Generated by Django 2.0 on 2019-08-08 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20190808_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.EmailValidator(message='Enter correct email id ')])),
                ('service', models.CharField(max_length=30)),
                ('budget', models.FloatField()),
                ('message', models.CharField(max_length=450)),
            ],
            options={
                'db_table': 'enquiry_form',
            },
        ),
        migrations.DeleteModel(
            name='EnquiryForm',
        ),
    ]
